import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignUp, SignInButton, SignUpButton, SignOutButton, SignIn, useUser } from "@clerk/nextjs";
import grid1 from "./"

const Home: NextPage = () => {
  
  const user = useUser();
  
  const { data } = api.accolades.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Accolades</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#DBA349] to-[#501685]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-20 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Accolades <span className="text-[hsl(280,100%,70%)]">&</span> Outcomes
          </h1>
          <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
          </div>
          <div>
            {data?.map((accolades) => (
              <div key={accolades.id}>{accolades.accolade}{accolades.institution}{accolades.comments}</div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
