
import Link from 'next/link'
import '../styles/globals.css'
import { Providers } from './providers'
import { LoginButton, LogoutButton } from './auth'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'
import Appbar from '~/app/Appbar'

export const metadata = {
  title: 'NYU Awards',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <html lang="en">
      <body>
      <Providers><Appbar />{children}</Providers>
      </body>
    </html>
    </>
  )
}