
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from "react-toastify";
import '../styles/globals.css'
import { Providers } from './providers'
import Appbar from '~/app/Appbar'

export const metadata = {
  title: 'NYU Awards',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <html lang="en">
      <body>
      <Providers>
        <Appbar />
        {children}

      <ToastContainer 
        position="top-center"
        autoClose={3000}
        hideProgressBar={false}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        theme="light"
        />
      </Providers>
      </body>
    </html>
    </>
  )
}
